# Operations file for clifford algebra
# Supposed to describe set of operations...
# Must be limited to the operations provided by the environment
# Lets define: operand1..n
# Issue: Limiting the operand types...
# Defining blades, it must be possible to add blades...

addOperation("mirror", operand1*operand2*operand1, [[blade1], [blade1]])
